/** The ad platforms we report on. Anything else is "direct / unattributed". */
export const AD_SOURCES = ["google", "koah", "facebook"] as const;
export type AdSource = (typeof AD_SOURCES)[number];

/**
 * Normalizes a raw utm_source value ("Google ", "KOAH" -> "google", "koah").
 * Unknown values return null so typos don't create phantom dashboard rows;
 * the raw value is still stored for debugging.
 */
export function normalizeSource(raw: string | null | undefined): AdSource | null {
  if (!raw) return null;
  const v = raw.trim().toLowerCase();
  return (AD_SOURCES as readonly string[]).includes(v) ? (v as AdSource) : null;
}

/**
 * Decides which platform a touch belongs to. A Koah click id (kad_cid) is
 * stronger evidence than a UTM tag, because UTMs are hand-written and often
 * wrong while click ids are generated by the ad server.
 */
export function resolveTouchSource(utmSource: string | null | undefined, clickId: string | null | undefined): AdSource | null {
  if (clickId) return "koah";
  return normalizeSource(utmSource);
}
