-- ============================================================================
-- 001_init: event ingestion + attribution data model
--
-- Four tables, each with one job:
--   raw_events   append-only log of everything we received (pixel + API). Never updated.
--   touches      one row per ad click / landing ("touchpoint"). The thing we attribute TO.
--   conversions  one row per *logical* conversion, merged across pixel + API by event_id.
--   orders       the store's own business records (what a real backend would have anyway).
--
-- Attribution is NOT stored; it is computed at query time by joining conversions
-- to touches under a chosen model. That makes models switchable and re-runnable.
-- ============================================================================

CREATE TABLE raw_events (
  id            BIGSERIAL PRIMARY KEY,
  advertiser_id TEXT        NOT NULL,
  via           TEXT        NOT NULL CHECK (via IN ('pixel', 'api')),  -- which channel delivered it
  event_name    TEXT        NOT NULL,                                  -- PageView, ViewContent, AddToCart, InitiateCheckout, Purchase
  event_id      TEXT        NOT NULL,                                  -- client/server generated; dedupe + pixel/API merge key
  user_id       TEXT        NOT NULL,                                  -- first-party persistent ID (HTTP-only cookie)
  tab_id        TEXT,                                                  -- per-tab ID (sessionStorage); NULL for API events
  touch_id      TEXT,                                                  -- the tab's active ad touch, if any
  page_url      TEXT,
  referrer      TEXT,
  user_agent    TEXT,
  is_bot        BOOLEAN     NOT NULL DEFAULT false,
  properties    JSONB       NOT NULL DEFAULT '{}',                     -- value, currency, products, order_id, ...
  occurred_at   TIMESTAMPTZ NOT NULL,                                  -- when it happened (server receive time, or API event_time)
  received_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- The same event delivered twice by the same channel (retries, beacon + fetch) is stored once.
  UNIQUE (advertiser_id, via, event_id)
);
CREATE INDEX raw_events_debugger_idx ON raw_events (advertiser_id, received_at DESC, id DESC);
CREATE INDEX raw_events_funnel_idx   ON raw_events (advertiser_id, event_name, occurred_at) WHERE NOT is_bot;
CREATE INDEX raw_events_touch_idx    ON raw_events (touch_id);

CREATE TABLE touches (
  touch_id      TEXT PRIMARY KEY,                -- generated by the pixel when it sees UTM params / a click id
  advertiser_id TEXT        NOT NULL,
  user_id       TEXT        NOT NULL,
  tab_id        TEXT,
  source        TEXT,                            -- normalized: google | koah | facebook | NULL (unknown)
  source_raw    TEXT,
  medium        TEXT,
  campaign      TEXT,
  content       TEXT,
  click_id      TEXT,                            -- kad_cid: Koah's click identifier
  landing_url   TEXT,
  is_bot        BOOLEAN     NOT NULL DEFAULT false,
  occurred_at   TIMESTAMPTZ NOT NULL
);
-- "Most recent touch for this user before time T" (lookback-window models).
CREATE INDEX touches_user_time_idx ON touches (advertiser_id, user_id, occurred_at DESC);
CREATE INDEX touches_time_idx      ON touches (advertiser_id, occurred_at);

CREATE TABLE conversions (
  advertiser_id TEXT        NOT NULL,
  event_id      TEXT        NOT NULL,
  event_name    TEXT        NOT NULL,
  user_id       TEXT        NOT NULL,
  touch_id      TEXT,                            -- only the pixel knows this (tab context)
  click_id      TEXT,                            -- the API can carry this (from the kad_cid cookie)
  order_id      TEXT,
  value_cents   INTEGER,
  currency      TEXT,
  products      JSONB,
  page_url      TEXT,
  received_via  TEXT[]      NOT NULL,            -- {pixel}, {api} or {api,pixel}: proves dedupe worked
  occurred_at   TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (advertiser_id, event_id)
);
CREATE INDEX conversions_time_idx ON conversions (advertiser_id, occurred_at);

CREATE TABLE orders (
  order_id      TEXT PRIMARY KEY,
  user_id       TEXT        NOT NULL,
  items         JSONB       NOT NULL,            -- [{product_id, name, quantity, unit_price_cents}]
  total_cents   INTEGER     NOT NULL,
  currency      TEXT        NOT NULL,
  event_id      TEXT        NOT NULL UNIQUE,     -- shared with the pixel's Purchase event for dedupe
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
