import type { Product } from "../api";

/**
 * Course poster: an illustrated image per course, generated by
 * web/scripts/posters.mjs into /public/posters (800px and 1600px wide).
 * Posters carry no text; the course title stays real HTML next to them.
 */
export default function CourseCover({
  product,
  size = "md",
  priority = false,
}: {
  product: Product;
  size?: "sm" | "md" | "lg";
  priority?: boolean;
}) {
  const sizes = size === "sm" ? "96px" : size === "lg" ? "(max-width: 960px) 100vw, 360px" : "(max-width: 720px) 100vw, 320px";
  return (
    <div className={`poster poster-${size}`}>
      <img
        src={`/posters/${product.id}-800.jpg`}
        srcSet={`/posters/${product.id}-800.jpg 800w, /posters/${product.id}-1600.jpg 1600w`}
        sizes={sizes}
        width={800}
        height={500}
        alt=""
        loading={priority ? "eager" : "lazy"}
        decoding="async"
      />
    </div>
  );
}
